# config.toml

[exclude-checks]
top-level = [
    "c_count",
    "dao",
    "langcode",
    "language",
    "materialspec",
    "url",
]

component = [
    "dao_desc",
    "dao_link",
    "dao_title",
    "langcode",
    "materialspec",
    "unitid",
]

[dao]
valid-roles = [
    "image-service",
    "audio-service",
    "video-service",
    "external-link",
    "non-url",
]

[all-html]
fields = [
    "material_type",
    "names",
    "place",
]
