# config.toml

[exclude-checks]
top-level = [
    "altformavail",
    "c_count",
    "dao",
    "url",
]

container = [
    "dao_desc",
    "dao_link",
    "dao_title",
    "unitid",
]

[dao]
valid-roles = [
    "image-service",
    "audio-service",
    "video-service",
    "external-link",
]
