# config.toml

[exclude-checks]
top-level = [
    "c_count",
    "dao",
    "langcode",
    "language",
    "url",
]

component = [
    "dao_desc",
    "dao_link",
    "dao_title",
    "langcode",
    "unitid",
]

[dao]
valid-roles = [
    "image-service",
    "audio-service",
    "video-service",
    "external-link",
    "non-url",
]

[all-html]
fields = [
    "material_type",
    "names",
    "place",
]

[checks]
top-level = [
    "abstract",
    "accessrestrict",
    "accruals",
    "acqinfo",
    "altformavail",
    "appraisal",
    "author",
    "bioghist",
    "chronlist",
    "chronlist_heading",
    "collection",
    "collection_unitid",
    "corpname",
    "creation_date",
    "creator",
    "creators",
    "custodhist",
    "eadid",
    "famname",
    "function",
    "genreform",
    "geogname",
    "heading",
    "langusage",
    "material_type",
    "materialspec",
    "name",
    "names",
    "note",
    "occupation",
    "originalsloc",
    "persname",
    "phystech",
    "place",
    "prefercite",
    "repository",
    "scopecontent",
    "separatedmaterial",
    "sponsor",
    "subject",
    "subjects",
    "subtitle",
    "title",
    "unitdate_all",
    "unitid",
    "unittitle",
    "userestrict",
]

component = [
    "accessrestrict",
    "accessrestrict_heading",
    "accruals",
    "accruals_heading",
    "acqinfo",
    "acqinfo_heading",
    "altformavail",
    "altformavail_heading",
    "appraisal",
    "appraisal_heading",
    "arrangement",
    "arrangement_heading",
    "bioghist",
    "bioghist_heading",
    "container",
    "corpname",
    "creator",
    "custodhist",
    "custodhist_heading",
    "dao",
    "dimensions",
    "extent",
    "famname",
    "fileplan",
    "fileplan_heading",
    "function",
    "genreform",
    "geogname",
    "language",
    "materialspec",
    "name",
    "occupation",
    "odd",
    "odd_heading",
    "originalsloc",
    "originalsloc_heading",
    "otherfindaid",
    "otherfindaid_heading",
    "persname",
    "physfacet",
    "physloc",
    "phystech",
    "phystech_heading",
    "prefercite",
    "prefercite_heading",
    "processinfo",
    "processinfo_heading",
    "relatedmaterial",
    "relatedmaterial_heading",
    "scopecontent",
    "scopecontent_heading",
    "separatedmaterial",
    "separatedmaterial_heading",
    "subject",
    "title",
    "unitdate",
    "unittitle",
    "userestrict",
    "userestrict_heading",
]
