# excludes.toml

[top]
checks = [
    "altformavail",
    "c_count",
    "dao",
    "url",
]

[container]
checks = [
    "dao_desc",
    "dao_link",
    "dao_title",
    "unitid",
]

[dao]
roles = [
    "image-service",
    "audio-service",
    "video-service",
    "external-link",
]
